### ISSUE TITLE
appxtrue computes L2 errors even if the solution is not dense

### ISSUE THREAD

**Issue by nathanaelbosch** [SciML/DiffEqDevTools.jl#97]
For `appxtrue(::AbstractODESolution, ::TestSolution)` see these lines: 
https://github.com/SciML/DiffEqDevTools.jl/blob/66db9580c2271c50cb1b70dbc2bb8f8bd907f4d4/src/test_solution.jl#L48-L61

In comparison, `appxtrue(::AbstractODESolution, ::AbstractODESolution)` at least has `timeseries_errors` and `dense_errors` keyword arguments to specify if the corresponding errors should be computed or not. But even there, the keyword is not taken 100% seriously: if `sol2.dense`, then the timeseries error is computed even if the keyword explicitly says otherwise:
https://github.com/SciML/DiffEqDevTools.jl/blob/66db9580c2271c50cb1b70dbc2bb8f8bd907f4d4/src/test_solution.jl#L83-L87

From my perspective, the logic in these functions should be changed towards the following:
- Have keyword arguments `timeseries_errors` and `dense_errors`, and compute the corresponding errors _only if the keyword argument is true_
- Compute dense errors _only if both solutions are dense_ (as opposed to the current approach that checks only if `sol2` is dense)
- Possibly: Compute timeseries errors only if the solution is of length >2 (so that it is not computed if `save_everystep=false`)

**Comment by ChrisRackauckas** [comment]
Yeah this could be added. Though IIRC the issue is that when benchmarking, you want to be able to show what the L2 error would be for methods which do not have interpolation overloads to measure that effect. The biggest one being that Sundials doesn't have the ability to do post-solution interpolation other than via Hermite (since there is no access to the reconstruction), so we do need some kind of fallback to just compute the errors anyways if asked for.

**Comment by ChrisRackauckas** [comment]
I believe this has good handling now with the error choices.
